require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/armor_accessories", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # ArmorAccessory. As you add validations to ArmorAccessory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # ArmorAccessoriesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      ArmorAccessory.create! valid_attributes
      get armor_accessories_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      armor_accessory = ArmorAccessory.create! valid_attributes
      get armor_accessory_url(armor_accessory), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ArmorAccessory" do
        expect {
          post armor_accessories_url,
               params: { armor_accessory: valid_attributes }, headers: valid_headers, as: :json
        }.to change(ArmorAccessory, :count).by(1)
      end

      it "renders a JSON response with the new armor_accessory" do
        post armor_accessories_url,
             params: { armor_accessory: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ArmorAccessory" do
        expect {
          post armor_accessories_url,
               params: { armor_accessory: invalid_attributes }, as: :json
        }.to change(ArmorAccessory, :count).by(0)
      end

      it "renders a JSON response with errors for the new armor_accessory" do
        post armor_accessories_url,
             params: { armor_accessory: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested armor_accessory" do
        armor_accessory = ArmorAccessory.create! valid_attributes
        patch armor_accessory_url(armor_accessory),
              params: { armor_accessory: new_attributes }, headers: valid_headers, as: :json
        armor_accessory.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the armor_accessory" do
        armor_accessory = ArmorAccessory.create! valid_attributes
        patch armor_accessory_url(armor_accessory),
              params: { armor_accessory: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the armor_accessory" do
        armor_accessory = ArmorAccessory.create! valid_attributes
        patch armor_accessory_url(armor_accessory),
              params: { armor_accessory: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested armor_accessory" do
      armor_accessory = ArmorAccessory.create! valid_attributes
      expect {
        delete armor_accessory_url(armor_accessory), headers: valid_headers, as: :json
      }.to change(ArmorAccessory, :count).by(-1)
    end
  end
end
